apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: bitcoind
spec:
  selector:
    matchLabels:
      app: bitcoind
  serviceName: "bitcoind-headless"
  template:
    metadata:
      labels:
        app: bitcoind
    spec:
      securityContext:
        fsGroup: 1000
      containers:
      - name: bitcoind
        image: lncm/bitcoind:v28.0
        args: [
          "--datadir=/data",
          "--txindex",
          "-chain={{ .Values.chain }}",
          "-rpcport=18443",
          "-rpcallowip=0.0.0.0/0",
          "-rpcbind=0.0.0.0",
          "-rpcauth=test:2c14712fc3137a12f4bd7d0c8ae1b895$990a2ebe5f7eb7893a68299c5a09bc22258855704aa8d74a21e4e01e35a777c0"
        ]
        volumeMounts:
        - mountPath: /data
          name: data
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      storageClassName: {{ .Values.storageClassName }}
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: {{ .Values.bitcoind.storage.size }}
