apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: laos-btc
  labels:
    app: laos-btc
spec:
  selector:
    matchLabels:
      app: laos-btc
  serviceName: "laos-btc-headless"
  template:
    metadata:
      labels:
        app: laos-btc
    spec:
      securityContext:
        fsGroup: 1000
      containers:
      - name: laos-btc
        image: freeverseio/laos-btc:{{ .Values.tag }}
        imagePullPolicy: Always
        args:
          - --data-dir
          - /data
          - --index-sats
          - --index-brc721
          - --no-index-inscriptions 
          - --bitcoin-rpc-url
          - http://bitcoind:18443
          - --bitcoin-rpc-username
          - test
          - --bitcoin-rpc-password
          - test
          - --chain={{ .Values.chain }} 
          - server
          - --http-port=8080
        env:
        - name: RUST_LOG
          value: {{ .Values.laosbtc.logLevel }}
{{- if .Values.laosbtc.storage }}
        volumeMounts:
        - mountPath: /data
          name: data
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: {{ .Values.storageClassName }}
      resources:
        requests:
          storage: {{ .Values.laosbtc.storage.size }}
{{- end }}
